using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using Xunit;
using PRN232.Plagiarism.Application.Services;

namespace PRN232.Plagiarism.Tests;

public class RoslynPlagiarismScannerTests : IDisposable
{
    private readonly string _workspaceRoot;
    private readonly RoslynPlagiarismScanner _scanner;

    public RoslynPlagiarismScannerTests()
    {
        _workspaceRoot = Path.Combine(Path.GetTempPath(), "prn232-plagiarism-tests", Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(_workspaceRoot);
        _scanner = new RoslynPlagiarismScanner();
    }

    [Fact]
    public async Task ScanAsync_ShouldReturnNoViolations_WhenCodeIsClean()
    {
        // Arrange
        WriteFile(Path.Combine(_workspaceRoot, "CleanController.cs"), 
            """
            using System;
            using Microsoft.AspNetCore.Mvc;

            public class CleanController : ControllerBase
            {
                public IActionResult Index() => Ok("Hello World");
            }
            """);

        var bannedKeywords = new List<string> { "Dapper", "SqlConnection", "SqlCommand" };

        // Act
        var violations = await _scanner.ScanAsync(_workspaceRoot, bannedKeywords);

        // Assert
        Assert.Empty(violations);
    }

    [Fact]
    public async Task ScanAsync_ShouldDetectBannedUsingDirective()
    {
        // Arrange
        WriteFile(Path.Combine(_workspaceRoot, "DbService.cs"), 
            """
            using System;
            using Dapper;

            public class DbService
            {
                // Clean code
            }
            """);

        var bannedKeywords = new List<string> { "Dapper" };

        // Act
        var violations = await _scanner.ScanAsync(_workspaceRoot, bannedKeywords);

        // Assert
        Assert.Single(violations);
        Assert.Equal("DbService.cs", violations[0].FileName);
        Assert.Equal("Dapper", violations[0].BannedKeyword);
        Assert.Equal(2, violations[0].LineNumber);
        Assert.Contains("using Dapper;", violations[0].CodeSnippet);
    }

    [Fact]
    public async Task ScanAsync_ShouldDetectBannedIdentifierName()
    {
        // Arrange
        WriteFile(Path.Combine(_workspaceRoot, "Repository.cs"), 
            """
            using System.Data;

            public class Repository
            {
                public void GetData()
                {
                    SqlConnection conn = new SqlConnection("ConnectionString");
                }
            }
            """);

        var bannedKeywords = new List<string> { "SqlConnection" };

        // Act
        var violations = await _scanner.ScanAsync(_workspaceRoot, bannedKeywords);

        // Assert
        Assert.NotEmpty(violations);
        Assert.Contains(violations, v => v.BannedKeyword == "SqlConnection" && v.LineNumber == 7);
    }

    [Fact]
    public async Task ScanAsync_ShouldDetectSubstringBannedIdentifier()
    {
        // Arrange
        WriteFile(Path.Combine(_workspaceRoot, "MyRepository.cs"), 
            """
            public class MyRepository
            {
                public void Connect()
                {
                    var connection = new MySqlConnection();
                }
            }
            """);

        var bannedKeywords = new List<string> { "SqlConnection" };

        // Act
        var violations = await _scanner.ScanAsync(_workspaceRoot, bannedKeywords);

        // Assert
        Assert.NotEmpty(violations);
        Assert.Contains(violations, v => v.BannedKeyword == "SqlConnection" && v.CodeSnippet.Contains("MySqlConnection"));
    }

    [Fact]
    public async Task ScanAsync_ShouldIgnoreAutogeneratedAndBuildFolders()
    {
        // Arrange
        var binDir = Path.Combine(_workspaceRoot, "bin", "Debug");
        var objDir = Path.Combine(_workspaceRoot, "obj");
        var migrationDir = Path.Combine(_workspaceRoot, "Migrations");

        WriteFile(Path.Combine(binDir, "Library.cs"), "using Dapper;");
        WriteFile(Path.Combine(objDir, "Temp.cs"), "using Dapper;");
        WriteFile(Path.Combine(migrationDir, "20260704_Init.cs"), "using Dapper;");
        WriteFile(Path.Combine(_workspaceRoot, "DesignerFile.Designer.cs"), "using Dapper;");

        var bannedKeywords = new List<string> { "Dapper" };

        // Act
        var violations = await _scanner.ScanAsync(_workspaceRoot, bannedKeywords);

        // Assert
        Assert.Empty(violations);
    }

    private void WriteFile(string path, string content)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, content);
    }

    public void Dispose()
    {
        if (Directory.Exists(_workspaceRoot))
        {
            Directory.Delete(_workspaceRoot, recursive: true);
        }
    }
}
